# -*- coding: utf-8 -*-
"""microdados_ifes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DF_RV3ViZ-t3uT_WKS_MEyKacf7TuRXt
"""

"""
ETL - FASE 1: EXTRAÇÃO (Extract)
Trabalho de Conclusão de Curso - IFES
Descrição: Este script lê múltiplos ficheiros PDF contendo os editais
de aprovação do IFES e consolida-os num único ficheiro CSV bruto.
"""

import pandas as pd
import tabula
import os
import re

# --- 1. CONFIGURAÇÃO DE DIRETÓRIOS ---
# Altere para o caminho onde estão as suas pastas de PDFs
caminho_base = r"./dados"
pastas_de_dados = ["PDFs_IFES_2025", "PDFs_IFES_2024", "PDFs_IFES_2023", "PDFs_IFES_2022"]
arquivo_saida = os.path.join(caminho_base, "dados_ifes_brutos_consolidados.csv")
lista_dfs = []

print("--- INICIANDO SCRIPT DE EXTRAÇÃO (ETL - FASE 1) ---")

# --- 2. PROCESSAMENTO DE EXTRAÇÃO ---
for nome_pasta in pastas_de_dados:
    caminho_pasta_ano = os.path.join(caminho_base, nome_pasta)

    if not os.path.exists(caminho_pasta_ano):
        print(f"[AVISO] Pasta não encontrada, pulando: {nome_pasta}")
        continue

    try:
        # Extrai o ano do nome da pasta (ex: 2024)
        ano = re.search(r'\d{4}', nome_pasta).group()
        print(f"\n--- Processando pasta do ANO: {ano} ---")
    except AttributeError:
        continue

    for nome_arquivo in os.listdir(caminho_pasta_ano):
        if nome_arquivo.endswith(".pdf"):
            caminho_pdf = os.path.join(caminho_pasta_ano, nome_arquivo)

            # Extração de Metadados do nome do ficheiro
            partes_nome = nome_arquivo.replace(".pdf", "").split("-")
            campus = partes_nome[0].title()

            try:
                idx_integrado_em = partes_nome.index("em")
                curso = " ".join(partes_nome[idx_integrado_em + 1:]).title()
                # Limpeza de lixo no nome do curso
                curso = re.sub(r' (Matutino|Vespertino|Integral|Noturno|Resultado|Geral).*$', '', curso, flags=re.IGNORECASE)
            except ValueError:
                curso = "Nao Identificado"

            print(f"Lendo: {nome_arquivo} | Campus: {campus} | Curso: {curso}")

            try:
                # Leitura do PDF via Tabula
                dfs_paginas = tabula.read_pdf(
                    caminho_pdf,
                    pages='all',
                    stream=True,
                    encoding='latin-1',
                    pandas_options={'header': None}
                )

                if not dfs_paginas:
                    continue

                df_temp = pd.concat([df for df in dfs_paginas if not df.empty], ignore_index=True)

                # Normalização das colunas
                df_temp.columns = [f"COL_{i}" for i in range(len(df_temp.columns))]
                df_temp['ANO'] = ano
                df_temp['CAMPUS'] = campus
                df_temp['CURSO'] = curso

                lista_dfs.append(df_temp)

            except Exception as e:
                print(f"    [ERRO] Falha ao processar {nome_arquivo}: {e}")

# --- 3. EXPORTAÇÃO (Save) ---
if lista_dfs:
    print("\nConsolidando os dados num único DataFrame...")
    df_final = pd.concat(lista_dfs, ignore_index=True)
    df_final.to_csv(arquivo_saida, index=False, encoding='utf-8-sig')
    print(f"[SUCESSO] Ficheiro bruto gerado: {arquivo_saida}")
else:
    print("[AVISO] Nenhum dado foi extraído.")