# -*- coding: utf-8 -*-
"""microdados_ifes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DF_RV3ViZ-t3uT_WKS_MEyKacf7TuRXt
"""

"""
ETL - FASE 2: TRANSFORMAÇÃO (Transform)
Trabalho de Conclusão de Curso - IFES
Descrição: Este script limpa a base de dados bruta, filtra apenas os candidatos
"Aprovados" ou "Classificados", e calcula a Tabela de Ouro (KPIs de Corte).
"""

import pandas as pd
import numpy as np
import os

# --- 1. CONFIGURAÇÃO ---
caminho_base = r"./dados"
arquivo_csv_mestre = os.path.join(caminho_base, "dados_ifes_brutos_consolidados.csv")
saida_corte_geral = os.path.join(caminho_base, "TENDENCIA_NOTAS_CORTE_LIMPO.csv")

print("--- INICIANDO LIMPEZA E CÁLCULO DE KPIs (ETL - FASE 2) ---")

try:
    # low_memory=False para evitar alertas de tipagem do Pandas
    df = pd.read_csv(arquivo_csv_mestre, low_memory=False)
except FileNotFoundError:
    print(f"[ERRO] Arquivo não encontrado: {arquivo_csv_mestre}")
    exit()

# --- 2. DATA WRANGLING E FILTRAGEM ---
# Filtrar apenas alunos aprovados para descobrir a nota do último colocado
status_limpos = ['Aprovado', 'Classificado']

# Assegurar que a coluna de RESULTADO existe e tem o nome correto (Ajuste conforme o seu dataset)
col_resultado = 'RESULTADO' if 'RESULTADO' in df.columns else df.columns[-1]
col_nota = 'NOTA_FINAL' if 'NOTA_FINAL' in df.columns else df.columns[-2]

df_clean = df[df[col_resultado].isin(status_limpos)].copy()
df_clean[col_nota] = pd.to_numeric(df_clean[col_nota], errors='coerce')
df_clean = df_clean.dropna(subset=[col_nota])

print(f"Total de candidatos aprovados/classificados processados: {len(df_clean)}")

# --- 3. CÁLCULO DOS KPIs (TABELA DE OURO) ---
print("Calculando Notas de Corte (Mínimo) e Desempenho Percentual...")

df_kpis = df_clean.groupby(['ANO', 'CAMPUS', 'CURSO'])[col_nota].agg(
    NOTA_MAXIMA='max',
    PONTO_DE_CORTE='min', # Nota do último aprovado
    MEDIA_CURSO='mean'
).reset_index()

# Normalização de Escala (As provas do IFES variaram entre 500 e 400 pontos nos últimos anos)
# Para uniformizar, criamos um índice de desempenho percentual baseado na prova daquele ano.
def calcular_percentual(row):
    # Se o ano for menor que 2024, a prova valia 500. Senão, 400.
    teto_prova = 500.0 if int(row['ANO']) < 2024 else 400.0
    return row['PONTO_DE_CORTE'] / teto_prova

df_kpis['DESEMPENHO_CORTE'] = df_kpis.apply(calcular_percentual, axis=1)

# --- 4. EXPORTAÇÃO ---
# Ordenar para facilitar a leitura visual
df_kpis = df_kpis.sort_values(by=['ANO', 'CAMPUS', 'CURSO'], ascending=[False, True, True])
df_kpis.to_csv(saida_corte_geral, index=False, encoding='utf-8-sig')

print(f"[SUCESSO] Tabela de Ouro gerada com sucesso: {saida_corte_geral}")