# -*- coding: utf-8 -*-
"""microdados_ifes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DF_RV3ViZ-t3uT_WKS_MEyKacf7TuRXt
"""

"""
ETL - FASE 3: CARGA (Load)
Trabalho de Conclusão de Curso - IFES
Descrição: Conecta-se ao banco de dados relacional na nuvem (Supabase)
e faz a inserção (ou atualização) da Tabela de Ouro gerada na Fase 2.
"""

import pandas as pd
import psycopg2
from psycopg2 import extras
import os

# --- 1. CREDENCIAIS ---
# ATENÇÃO: Nunca suba esta senha para o GitHub público! Use variáveis de ambiente num projeto real.
DB_URI = "postgresql://postgres:<SUBA_SENHA_AQUI>@db.efandhnqvcukmvfsoeoz.supabase.co:5432/postgres"

caminho_base = r"./dados"
arquivo_csv = os.path.join(caminho_base, "TENDENCIA_NOTAS_CORTE_LIMPO.csv")

print("--- INICIANDO UPLOAD PARA O SUPABASE (ETL - FASE 3) ---")

try:
    df = pd.read_csv(arquivo_csv)

    # Remover duplicatas exatas para não violar a Primary Key do Banco de Dados
    df = df.drop_duplicates(subset=['ANO', 'CAMPUS', 'CURSO'], keep='first')
    print(f"CSV preparado para envio: {len(df)} registos únicos.")

    # Conectar ao Postgres do Supabase
    conn = psycopg2.connect(DB_URI)
    cur = conn.cursor()

    # Recriar Tabela e Configurar Segurança (RLS - Row Level Security)
    print("Configurando esquema da tabela 'kpis_ifes'...")
    cur.execute("""
        DROP TABLE IF EXISTS kpis_ifes;

        CREATE TABLE kpis_ifes (
            ano INT,
            campus TEXT,
            curso TEXT,
            nota_maxima REAL,
            ponto_de_corte REAL,
            desempenho_corte REAL,
            PRIMARY KEY (ano, campus, curso)
        );

        -- Permite que a aplicação Web leia os dados anonimamente
        ALTER TABLE kpis_ifes ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "Permitir leitura publica" ON kpis_ifes FOR SELECT USING (true);
    """)
    conn.commit()

    # Preparar as tuplas para o envio em lote (Batch Insert)
    registros = []
    for _, row in df.iterrows():
        registros.append((
            int(row['ANO']),
            str(row['CAMPUS']),
            str(row['CURSO']),
            float(row['NOTA_MAXIMA']),
            float(row['PONTO_DE_CORTE']),
            float(row['DESEMPENHO_CORTE'])
        ))

    # Query de Inserção com tratamento de conflito (Upsert)
    query = """
        INSERT INTO kpis_ifes (ano, campus, curso, nota_maxima, ponto_de_corte, desempenho_corte)
        VALUES %s
        ON CONFLICT (ano, campus, curso)
        DO UPDATE SET
            nota_maxima = EXCLUDED.nota_maxima,
            ponto_de_corte = EXCLUDED.ponto_de_corte,
            desempenho_corte = EXCLUDED.desempenho_corte
    """

    print("A enviar dados...")
    extras.execute_values(cur, query, registros)
    conn.commit()

    print("[SUCESSO ABSOLUTO] Os dados estão online e prontos para a Aplicação Web!")

except Exception as e:
    print(f"[ERRO CRÍTICO] Falha no processo: {e}")
finally:
    if 'conn' in locals() and conn:
        cur.close()
        conn.close()
        print("Conexão à nuvem encerrada com segurança.")